version: 0.2
phases:

pre_build:
commands:
- $(aws ecr get-login --region us-east-1 --no-include-email)
- REPOSITORY_URI=603132347502.dkr.ecr.us-east-1.amazonaws.com/spajam2021
- IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

build:
commands:
- docker build -t $REPOSITORY_URI:latest .
- docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

post_build:
commands:
- docker push $REPOSITORY_URI:latest
- docker push $REPOSITORY_URI:$IMAGE_TAG
