version: '3'
services:
  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: ["sh", "-c", "uvicorn app.main:app --reload --host 0.0.0.0 --port ${PORT}"]
  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      PGDATA: /pgdata
      POSTGRES_DB: todoroki-db
      POSTGRES_USER: todoroki
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/pgdata